name: Update Gacha Data

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两小时运行一次 (UTC时间)
  workflow_dispatch:  # 允许手动触发
  push:  # 当有代码推送时也运行
    branches: [ main ]

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code with write permissions
      uses: actions/checkout@v4
      with:
        # 使用具有写权限的PAT
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0  # 获取所有历史记录

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper and commit changes
      run: |
        python python.py --save-json gacha_data.json
        
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        
        git add gacha_data.json
        git commit -m "Auto-update gacha data $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
        
        # 使用PAT进行身份验证的推送
        git push https://${{ github.actor }}:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git main --force

    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}
      with:
        source-repo: git@github.com:${{ github.repository }}.git
        destination-repo: git@gitee.com:zisekongling/genshin-impact-kachi.git
        force: true  # 强制推送
